# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

repo_name: manifoldfinance/auction-platform-docs
repo_url: https://github.com/manifoldfinance/auction-platform-docs
site_author: Manifold Finance & 20squares
# yamllint disable-line rule:line-length
site_description: MEV Auction documentation for builders, searchers and liquid staking protocols.
site_name: XGA Auctions Documentation
site_url: https://docs.xga.com
# yamllint disable-line rule:line-length
copyright: Manifold Finance, Inc, 20squares UG, and contributors. Creative Commons Attribution-NonCommercial-NoDerivs 2.5
use_directory_urls: true

theme:
  name: material
#  custom_dir: .docs/overrides/
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # - navigation.instant.prefetch
    # - navigation.prune
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
# breadcrumbs
    - navigation.indexes
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
# keep TOC on righthand side enabled
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
#  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css

extra_javascript:
  - javascripts/extra.js
# mathjax snippet is loaded in extra.js
#  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  is_insider: true
  generator: false
  google:
    site_verification:
      - ''
    tag_manager: ''

plugins:
  - search:
      #separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      separator: '[\s\-\.\_]+'
      lang: 'en'
#  - macros:
#      module_name: .docs/macros/includes/main
  - blog:
      post_url_format: "{categories}/{slug}"
      post_url_max_categories: 2
  - neoteroi.mkdocsoad:
      use_pymdownx: true


markdown_extensions:
# Built-in
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
#  - pymdownx.tabbed:
#      slugify: !!python/object/apply:pymdownx.slugs.slugify
#        kwds:
#          case: lower
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      user: manifoldfinance
      repo: auction-platform-docs
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
      toc_depth: 3
  - neoteroi.spantable
  - neoteroi.cards

nav:
  - index.md
  - Developers:
      - Getting Started: Developers/index.md
      # - Auctioneer: Developers/auctioneer.md
      - Interface: Developers/interface.md
      - Builders & Searchers: Developers/builders.md
      - Testnet: Developers/testnet.md
      - Payment Methods: Developers/payment-methods.md
      - SDK: Developers/sdk.md
  - Learning:
  #    - Flashbots Comparison: Learning/flashbots-comparison.md
      - Auction Design: Learning/aup_auction.md
      - Forward Contracts: Learning/Forward-Contracts.md
  # Disable Article
  #      - 'Secondary Market': 'Learning/secondary-market.md'
  - Clients:
      - Overview: Clients/index.md
      - Clients: Clients/clients.md
      - Validators: Clients/validators.md
      - Configuration: Clients/configuration.md
      - Accounting: Clients/accounting.md
      - Relay: Clients/relay.md
      - Requirements: Clients/requirements.md
  - Relay:
      - SecureRpc Relay: Relay/index.md
      - Captive Insurance: Relay/captive-insurance.md
      - SecureRPC Relay: https://securerpc.com
  - API:
      - Overview: api/index.md
      - Relay: api/relay.md
      - Validator Self Report: api/self-report.md
      - Beta Auction: api/beta-auction.md
      - Bundle: api/bundle.md
      - Signature Scheme: api/signature-scheme.md
      - Reference:
          - Contract Design: Reference/contract_design.md
          - Contract Summary: Reference/contract_summary.md
          - Glossary: Reference/glossary.md
          - RPC Payload: Reference/rpc-payload.md
          - Constant Values: Reference/constants.md
          - ERC 6909: Reference/erc6909.md
  - Legal:
      - Legal/index.md
      - Compliance: Legal/CDD.md
      - Content Disclaimer: Legal/Content-Disclaimer.md
      - Disclosure Statement: Legal/Disclosure-Statement.md
      - Rulebook:
          - Bylaws: Rulebook/bylaws.md
          - Definitions: Rulebook/definitions.md
          - Settlement: Rulebook/delivery-and-settlement.md
          - General: Rulebook/general.md
          - Governance: Rulebook/governance.md
          - Clearing: Rulebook/network-clearing-participants.md
          - Obligations: Rulebook/obligations.md
          - Suspension: Rulebook/suspension.md
  - Blog:
      - blog/index.md
