# yamllint disable rule:document-start
# yamllint disable rule:line-length
# yamllint disable rule:comments-indentation
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

repo_name: manifoldfinance/docs-xga
repo_url: https://github.com/manifoldfinance/docs-xga
site_author: XGA Systems
# yamllint disable-line rule:line-length
site_description: XGA documentation for builders, searchers and liquid staking protocols.
site_name: eXtensible Gas Auctions Documentation
site_url: https://docs.xga.com
# yamllint disable-line rule:line-length
# Creative Commons Attribution-NonCommercial-NoDerivs 2.5
copyright: >
  Copyright &copy; 2024 XGA Systems, Inc.
use_directory_urls: true

theme:
  name: material
  custom_dir: overrides
  language: en
  logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.footer
    - navigation.instant.prefetch
    # - navigation.prune
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: fontawesome/solid/toggle-on
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: fontawesome/solid/toggle-off
        name: Switch to system preference

extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  is_insider: true
  generator: false
  analytics:
    provider: google
    property: G-RWSFY7TBD5
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
    cookies:
      analytics:
        name: Google Analytics
        checked: false
  social:
    - icon: fontawesome/solid/rss
      link: https://your.site/newsletter/0_newsletter_index/

plugins:
  - search:
      #separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      separator: '[\s\-\.\_]+'
      lang: 'en'
#  - macros:
#      module_name: .docs/macros/includes/main
# - blog:
#     post_url_format: "{categories}/{slug}"
#     post_url_max_categories: 2
  - neoteroi.mkdocsoad:
      use_pymdownx: true
  - tags
# Disable due to Cloudflare issues
# - git-revision-date-localized:
#     type: timeago
# - autolinks
# - section-index
# - mkdocs-newsletter

markdown_extensions:
  # Built-in
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      user: manifoldfinance
      repo: docs-xga
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
      toc_depth: 3
  - neoteroi.spantable
  - neoteroi.cards

nav:
  - index.md
  - Developers:
      - Getting Started: Developers/index.md
      - Walkthrough Guide: Developers/walkthrough.md
      # - Auctioneer: Developers/auctioneer.md
      - Interface: Developers/interface.md
      - Builders & Searchers: Developers/builders.md
      - Mainnet: Developers/mainnet.md
      - Testnet: Developers/testnet.md
      - Payment Methods: Developers/payment-methods.md
      - SDK: Developers/sdk.md
  - Learning:
  #    - Flashbots Comparison: Learning/flashbots-comparison.md
      - Auction Design: Learning/aup_auction.md
      - Primary Market: Learning/primary-market.md
      - Forward Contracts: Learning/Forward-Contracts.md
      - Preconfirmations: Learning/preconfirmations.md
  # Disable Article
  #      - 'Secondary Market': 'Learning/secondary-market.md'
  - Relay:
      - SecureRpc Relay: Relay/index.md
      - Captive Insurance: Relay/captive-insurance.md
      - SecureRPC Relay: https://securerpc.com
  - API:
      - Overview: api/index.md
      - Relay: api/relay.md
      - Validator Self Report: api/self-report.md
      - Beta Auction: api/beta-auction.md
      - Bundle: api/bundle.md
      - Signature Scheme: api/signature-scheme.md
      - Reference:
          - Contract Design: Reference/contract_design.md
          - Contract Summary: Reference/contract_summary.md
          - Glossary: Reference/glossary.md
          - RPC Payload: Reference/rpc-payload.md
          - Constant Values: Reference/constants.md
          - ERC 6909: Reference/erc6909.md
  - Clients:
      - Overview: Clients/index.md
      - Clients: Clients/clients.md
      - Validators: Clients/validators.md
      - Configuration: Clients/configuration.md
      - Accounting: Clients/accounting.md
      - Relay: Clients/relay.md
      - Requirements: Clients/requirements.md
  - Legal:
      - Legal/index.md
      - Compliance: Legal/CDD.md
      - Content Disclaimer: Legal/Content-Disclaimer.md
      - Disclosure Statement: Legal/Disclosure-Statement.md
      - Rulebook:
          - Bylaws: Rulebook/bylaws.md
          - Definitions: Rulebook/definitions.md
          - Settlement: Rulebook/delivery-and-settlement.md
          - General: Rulebook/general.md
          - Governance: Rulebook/governance.md
          - Clearing: Rulebook/network-clearing-participants.md
          - Obligations: Rulebook/obligations.md
          - Suspension: Rulebook/suspension.md